const overrides = [
  {
    id: "DASH_DASH.null",
    blockchain: "DASH",
    symbol: "DASH",
    image: "https://forrestgains.github.io/icons/dash.png",
    address: null,
    decimals: 8,
    name: null,
  },
  {
    id: "ZCASH_ZCASH.null",
    blockchain: "ZCASH",
    symbol: "ZCASH",
    image: "https://forrestgains.github.io/icons/zcash.png",
    address: null,
    decimals: 8,
    name: null,
  },
  {
    id: "CANTO_CANTO.null",
    blockchain: "CANTO",
    symbol: "CANTO",
    image: "https://forrestgains.github.io/icons/canto.png",
    address: null,
    decimals: 18,
    name: null,
  },
  {
    id: "CANTO_NOTE.0x4e71A2E537B7f9D9413D3991D37958c0b5e1e503",
    blockchain: "CANTO",
    symbol: "NOTE",
    image: "https://forrestgains.github.io/icons/note.png",
    address: "0x4e71A2E537B7f9D9413D3991D37958c0b5e1e503",
    decimals: 18,
    name: null,
  },
  {
    id: "CANTO_wCANTO.0x826551890Dc65655a0Aceca109aB11AbDbD7a07B",
    blockchain: "CANTO",
    symbol: "wCANTO",
    image: "https://forrestgains.github.io/icons/canto.png",
    address: "0x826551890Dc65655a0Aceca109aB11AbDbD7a07B",
    decimals: 18,
    name: null,
  },
];
